### ISSUE TITLE
Support Transformers? 

### ISSUE THREAD

**Issue by fzyzcjy** [pomonam/kronfluence#37]
Hi thank you for the project! From my naive understanding, https://arxiv.org/abs/2308.03296 (and more recent https://openreview.net/forum?id=1hQKHHUsMx) supports Transformers. Therefore, I wonder whether this package will support it as well?

**Comment by pomonam** [comment]
Thank you for leaving the issue! Yes we have some examples here: https://github.com/pomonam/kronfluence/tree/main/examples/openwebtext.

**Comment by fzyzcjy** [comment]
Thank you!

**Comment by fzyzcjy** [comment]
@pomonam Btw, what do you think of https://openreview.net/forum?id=1hQKHHUsMx - is it possible to have that in this library? Thanks again for the helpful project :)

**Comment by pomonam** [comment]
I think the models used in the paper are not publicly available, but we can do a similar analysis as what's done in the paper. We do have code for computing influence functions for 8B parameters model (in the link I shared above).

**Comment by fzyzcjy** [comment]
@pomonam I am too silly to only realize *just now* that (1) you are the author of the `Studying Large Language Model Generalization with Influence Functions` paper! so this repo must be able to analyze Transformers (originally looked at paper and find no link and thought no open source was done...) (2) the 2024 paper does not seem to change much from your paper. Thank you and sorry for disturbing!

**Comment by pomonam** [comment]
No worries! Thank you again for leaving the issue! Yes, we should be able to do an interesting analysis on language models with this repo :).
